name: Caller

on:
  push:

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  test:
    uses: elissiafellow/testprod/.github/workflows/test.yaml@main
    with:
      SERVICE_NAME: "prototype"
      FILE_PATH: "workload_eks/prototype1.yaml"
      DEPLOYMENT_FILES: |
        workload_eks/prototype1.yaml
        workload_eks/protoype2.yaml
    secrets: inherit